package com.cmind.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.data.repository.query.Param;

import com.cmind.entity.EmployeeExample;
import com.cmind.entity.Staff;
import com.cmind.entity.StaffExample;


@Mapper
public interface StaffMapper {
//    /**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
//	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
//	 */
//	long countByExample(StaffExample example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
//	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
//	 */
//	int deleteByExample(StaffExample example);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
//	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
//	 */
//	@Delete({ "delete from employee", "where id = #{id,jdbcType=INTEGER}" })
//	int deleteByPrimaryKey(Integer id);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
//	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
//	 */
//	@Insert({ "insert into employee (id, name, ", "password)",
//			"values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ", "#{password,jdbcType=VARCHAR})" })
//	int insert(Staff record);
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
//	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
//	 */
//	int insertSelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	List<Staff> selectByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Select({ "select", "employee_id, name, password , create_at ,create_user update_at , update_user", "from staff", "where employee_id = #{employeeId,jdbcType=CHAR}" })
	@ResultMap("com.cmind.mybatis.mapper.StaffMapper.BaseResultMap")
	Staff selectByPrimaryKey(String emplpyeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Staff record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByExample(@Param("record") Staff record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	int updateByPrimaryKeySelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Fri Jun 25 16:08:30 JST 2021
	 */
	@Update({ "update staff", "set update_at = #{updateAt,jdbcType=VARCHAR},", "update_user = #{updateUser,jdbcType=VARCHAR} where employee_id = #{employeeId}" })
	int updateByPrimaryKey(Staff record);

	@Select({
        "select * from staff where name = #{name} limit 1"
    })
    Staff selectByName(String name);

	@Select({
        "select employee_id, name, password , create_at ,create_user update_at , update_user from staff where employee_id = #{employeeId} limit 1"
    })
    Staff selectById(String employeeId);

}